version: "3.9"

x-env-variables:
  - &POSTGRES_USER ituscheduler
  - &POSTGRES_PASSWORD ituscheduler
  - &POSTGRES_DATABASE ituscheduler

x-backend-common: &backend-common
  image: ituscheduler
  platform: linux/x86_64
  build: .
  volumes:
    - ./ituscheduler:/ituscheduler/ituscheduler
    - ./fixtures:/ituscheduler/fixtures
  env_file: .env
  environment: &backend-common-environment
    ITUSCHEDULER_POSTGRES_HOST: postgres
    ITUSCHEDULER_POSTGRES_PORT: 5432
    ITUSCHEDULER_POSTGRES_USER: *POSTGRES_USER
    ITUSCHEDULER_POSTGRES_PASSWORD: *POSTGRES_PASSWORD
    ITUSCHEDULER_POSTGRES_DATABASE: *POSTGRES_DATABASE
    COLUMNS: 80
  tty: true

volumes:
  postgres:

services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: *POSTGRES_USER
      POSTGRES_PASSWORD: *POSTGRES_PASSWORD
      POSTGRES_DB: *POSTGRES_DATABASE

  web:
    <<: *backend-common
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      <<: *backend-common-environment
      CONTAINER_KIND: web
    restart: unless-stopped

  worker:
    <<: *backend-common
    depends_on:
      - beat
    environment:
      <<: *backend-common-environment
      CONTAINER_KIND: worker

  beat:
    <<: *backend-common
    depends_on:
      - postgres
    environment:
      <<: *backend-common-environment
      CONTAINER_KIND: beat
