# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.PositiveIntegerField()),
                ('course_code', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=20)),
                ('time_start', models.PositiveIntegerField()),
                ('time_finish', models.PositiveIntegerField()),
                ('room', models.PositiveIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('enrolled', models.PositiveSmallIntegerField()),
                ('reservation', models.CharField(max_length=50)),
                ('major_restriction', models.TextField()),
                ('prerequisites', models.TextField()),
                ('class_restriction', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
