# Generated by Django 3.2.7 on 2021-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210907_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teaching_method',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
