# Generated by Django 4.0.1 on 2022-02-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_teaching_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default='S22', on_delete=django.db.models.deletion.CASCADE, to='api.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('SU22', '2021-2022 Summer'), ('S22', '2021-2022 Spring'), ('F21', '2021-2022 Fall'), ('SU21', '2020-2021 Summer'), ('S21', '2020-2021 Spring'), ('F20', '2020-2021 Fall'), ('SU20', '2019-2020 Summer'), ('S20', '2019-2020 Spring'), ('F19', '2019-2020 Fall'), ('SU19', '2018-2019 Summer'), ('S19', '2018-2019 Spring'), ('F18', '2018-2019 Fall'), ('SU18', '2017-2018 Summer'), ('S18', '2017-2018 Spring'), ('F17', '2017-2018 Fall'), ('S17', '2016-2017 Spring')], default='S22', max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
