# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'get_latest_by': 'crn'},
        ),
        migrations.AlterField(
            model_name='course',
            name='crn',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
