# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
