# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170816_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AddField(
            model_name='course',
            name='n_classes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='building',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='crn',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_finish',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_start',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
