# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170816_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecode',
            old_name='created',
            new_name='refreshed',
        ),
    ]
