# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170811_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coursecode',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='crn',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coursecode',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
