# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170817_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecode',
            name='refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
