# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='my_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_schedule', to='scheduler.Schedule'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='schedules',
            field=models.ManyToManyField(related_name='schedules', to='scheduler.Schedule'),
        ),
    ]
