# Generated by Django 3.1.1 on 2020-09-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('scheduler', '0002_auto_20200924_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='my_semester',
            field=models.ForeignKey(default='SU20', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.semester'),
        ),
    ]
