# Generated by Django 3.1.1 on 2020-09-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200924_1359'),
        ('scheduler', '0003_auto_20200924_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='my_semester',
            field=models.ForeignKey(default='F20', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.semester'),
        ),
    ]
