# Generated by Django 2.1.4 on 2019-01-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='my_semester',
            field=models.ForeignKey(default='F18', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.Semester'),
        ),
    ]
