# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170811_2255'),
        ('scheduler', '0002_auto_20170812_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='schedules',
        ),
        migrations.AddField(
            model_name='schedule',
            name='courses',
            field=models.ManyToManyField(to='api.Course'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='my_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule'),
        ),
    ]
